### ISSUE TITLE
Bug Report: Responsividade e o Background

### ISSUE THREAD

**Issue by marvin3w** [leolopes-js/fullstack-projeto-portfolio-dev#1]
# Aprimorando a Responsividade e o Background do Seu Portfólio

Oi! 👋 gostei bastante do seu portfólio. É legal ver os conhecimento que aprendeu e aplicou nele! Mas notei algumas coisinhas que podem deixar seu site ainda mais atrativo, especialmente em telas maiores. Então tomei a iniciativa de te apontar o que vi e de sugerir um caminho para contornar, tudo bem?!

## O que eu percebi

Quando abri seu site em uma tela grande (maior que 1366px), vi uma faixa branca no lado direito. 

![Captura de tela 2024-11-24 202630](https://github.com/user-attachments/assets/3923fbd3-cf8f-4505-8065-7f047a40fa16)

Isso acontece porque as seções estão com uma largura fixa de 1366px. Para não chegar aqui e apenas apontar o problema, vou sugerir uma maneira de como resolver isso. 😉

### 1. Ajustando a largura das seções

Ao invés de usar `width: 1366px;` para definir a largura das seções, que tal tentar algo como isso:

```css
/* Estilo base para todas as telas */
.section {
  width: 100%;
  margin: 0 auto;
}
.container {
  max-width: 1366px;
}
```

Nesse caso será necessário adicionar uma div com a classe `container` dentro de cada seção. Isso fará com que o conteúdo fique centralizado e com uma largura máxima de 1366px, mas se ajustará para ocupar 100% da largura da tela em telas menores:

```html
<section class="section">
  <div class="container">
    <!-- Seu conteúdo aqui -->
  </div>
```

O código ficará um pouco mais verboso, mas vai garantir que seu site não fique deslocado para a esquerda em telas maiores que 1366px.

2. Melhorando o background

Fazer a mudança acima vai resolver o problema da faixa branca, mas ainda temos o detalhe da imagem de fundo ter um tamanho limitado. Que pode apresentar distorções em resoluções muito grandes. Mas pelo que vi, há alguma margem para que ela cresça sem perder a qualidade. Então nesse caso teria que fazer o teste de até que tamanho de tela a imagem se comporta bem e partir disso definir um tamanho fixo para ela, mostrando apenas a cor de fundo no tom da imagem, nas areas laterais que estrapolarem a largura máxima da imagem.

Para isso, você pode manter o uso `background-size: cover` e um media queries para ajustar o tamanho da imagem em telas maiores. Dá uma olhada:

```css

/* Estilo base para todas as telas */
.background-section {
  background-image: url('caminho/para/sua/imagem.jpg');
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  background-color: #sua-cor-aqui; /* Uma cor que combine com a imagem */
}

/* Configuração para as telas maiores que o tamanho que você testou, aqui add apenas um valor qualquer de ex. */
@media screen and (min-width: 1440px) {
  .background-section {
    background-size: 1440px auto;
  }
}
```

O que isso faz:
O `background-size: cover;` como está configurado faz a imagem preencher todo o espaço do elemento onde está presente.
A media query define um ponto onde a imagem para de crescer (1440px neste exemplo).
Em telas maiores que 1440px, a imagem fica com uma largura fixa, evitando que fique distorcida.
A cor de fundo garante que tudo fique bonito, mesmo se a imagem não cobrir tudo.

## Conclusão

Espero estar contribuindo de alguma maneira. Se eu me equivoquei em algo, ou se precisar de qualquer suporte, estou por aqui, só chamar.
